export EDITOR=vim

stty -ixon # disable Ctrl-S

# avoid Ctrl-D spam exitting shells
set -o ignoreeof

alias sl='ls'
alias lr='ls -lathr'

alias t='tmux'
alias tl='tmux list-sessions'
alias ta='tmux a -t'

alias view='vim -M'
function v {
    nvr --servername $NVIM_LISTEN_ADDRESS --nostart "$@"
}
function vwd {
    nvr --servername $NVIM_LISTEN_ADDRESS --nostart "$@" -c "cd $(pwd)"
}
alias r='ranger-cd'

export VIRTUALENVWRAPPER_PYTHON=$(which python3)
source $(which  virtualenvwrapper.sh)

alias b64decode="python3 -c 'import base64, sys; print(base64.b64decode(sys.argv[1]).decode())'"
alias b64encode="python3 -c 'import base64, sys; print(base64.b64encode(sys.argv[1].encode()).decode())'"

function treel { # tree view current directory
    tree -C "$@"
}

function tree-django {
    tree -C -I "__pycache__|static" "$@"
}

function tlr { # tail the last modified file in current folder
    local FILE="$(ls -At | head -n 1)"
    echo "---- ${FILE}:"
    tail -n 30 -f "$FILE"
}

function vlr { # edit last modified file in current folder
    local FILE="$(ls -At | head -n 1)"
    vim "$FILE"
}

function validate_fzf_choice {
    case "$1" in
        "") return 1;;
        + ) return 1;;
        +\n) return 1;;
        +\t) return 1;;
        *) return 0;;
    esac
}

function cd_virtualenv {
    local VENV=$(ls -d $HOME/.virtualenvs/*/ | cut -d/ -f 5 | fzf)
    if [ -n "$VENV" ]; then
        echo "$HOME/.virtualenvs/$VENV/lib/python3.7/site-packages"
        cd "$HOME/.virtualenvs/$VENV/lib/python3.7/site-packages"
    fi
}

function wo {
    local VENV=$(lsvirtualenv -b | fzf)
    if [ -n "$VENV" ]; then
        echo "$VENV"
        workon "$VENV"
    fi
}

function flutter-hotreload {
    while true; do
        find . -name *.dart | entr -dnp bash -c 'tmux send-keys -t :flutter_run r' /_
    done
}

function c {
    while true; do
        ls -aF
        echo ''
        pwd
        CHOICE=$(ls -aF | awk '{ if ($1!="./") print $1}' | fzf --height=5 --reverse)
        if [ -z "$CHOICE" ]; then
            break
        fi
        if [ -f "$CHOICE" ]; then
            v "$CHOICE"
        else
            cd "$CHOICE"
        fi
    done
}
